spring:
  application:
    name: eureka
  zipkin:
    baseUrl: http://127.0.0.1:9411/

server:
  port: 9091
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:9091/eureka/
